-- MINI HUBSUS360 - DML de amostra para reprodução
-- Execute depois de 01_ddl_experimental.sql, em um schema Oracle vazio.
-- A carga contém 13 tabelas e 21 perfis de internação, com amostras de 2023 a 2025.
-- Não representa a base completa do SIH/SUS nem reproduz toda a capacidade de leitos.
-- Os valores monetários usam literais numéricos com ponto decimal.
-- Para executar SET DEFINE/WHENEVER no SQL Developer, use Executar como Script (F5).
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- T_CATEGORIA_LEITO (66 registros)
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('1','CIRURGICO','BUCO MAXILO FACIAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('2','CIRURGICO','CARDIOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('3','CIRURGICO','CIRURGIA GERAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('4','CIRURGICO','ENDOCRINOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('5','CIRURGICO','GASTROENTEROLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('6','CIRURGICO','GINECOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('7','CIRURGICO','NEFROLOGIAUROLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('8','CIRURGICO','NEUROCIRURGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('9','CIRURGICO','OFTALMOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('10','CIRURGICO','ONCOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('11','CIRURGICO','ORTOPEDIATRAUMATOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('12','CIRURGICO','OTORRINOLARINGOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('13','CIRURGICO','PLASTICA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('14','CIRURGICO','QUEIMADO ADULTO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('15','CIRURGICO','QUEIMADO PEDIATRICO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('16','CIRURGICO','TORACICA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('17','CIRURGICO','TRANSPLANTE');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('18','CLINICO','AIDS');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('19','CLINICO','CARDIOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('20','CLINICO','CLINICA GERAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('21','CLINICO','DERMATOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('22','CLINICO','GERIATRIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('23','CLINICO','HANSENOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('24','CLINICO','HEMATOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('25','CLINICO','NEFROUROLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('26','CLINICO','NEONATOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('27','CLINICO','NEUROLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('28','CLINICO','ONCOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('29','CLINICO','PNEUMOLOGIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('30','CLINICO','QUEIMADO ADULTO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('31','CLINICO','QUEIMADO PEDIATRICO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('32','CLINICO','SAUDE MENTAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('33','COMPLEMENTAR','SUPORTE VENTILATORIO PULMONAR - COVID-19');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('34','COMPLEMENTAR','UNIDADE DE CUIDADOS INTERMEDIARIOS ADULTO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('35','COMPLEMENTAR','UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL CANGURU');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('36','COMPLEMENTAR','UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL CONVENCIONAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('37','COMPLEMENTAR','UNIDADE DE CUIDADOS INTERMEDIARIOS PEDIATRICO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('38','COMPLEMENTAR','UNIDADE INTERMEDIARIA NEONATAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('39','COMPLEMENTAR','UNIDADE ISOLAMENTO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('40','COMPLEMENTAR','UTI ADULTO - TIPO I');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('41','COMPLEMENTAR','UTI ADULTO - TIPO II');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('42','COMPLEMENTAR','UTI ADULTO - TIPO III');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('43','COMPLEMENTAR','UTI CORONARIANA TIPO II - UCO TIPO II');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('44','COMPLEMENTAR','UTI CORONARIANA TIPO III - UCO TIPO III');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('45','COMPLEMENTAR','UTI DE QUEIMADOS');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('46','COMPLEMENTAR','UTI NEONATAL - TIPO I');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('47','COMPLEMENTAR','UTI NEONATAL - TIPO II');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('48','COMPLEMENTAR','UTI NEONATAL - TIPO III');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('49','COMPLEMENTAR','UTI PEDIATRICA - TIPO I');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('50','COMPLEMENTAR','UTI PEDIATRICA - TIPO II');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('51','COMPLEMENTAR','UTI PEDIATRICA - TIPO III');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('52','HOSPITAL DIA','AIDS');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('53','HOSPITAL DIA','CIRURGICO/DIAGNOSTICO/TERAPEUTICO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('54','HOSPITAL DIA','FIBROSE CISTICA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('55','HOSPITAL DIA','GERIATRIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('56','HOSPITAL DIA','INTERCORRENCIA POS-TRANSPLANTE');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('57','HOSPITAL DIA','SAUDE MENTAL');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('58','OBSTETRICOS','OBSTETRICIA CIRURGICA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('59','OBSTETRICOS','OBSTETRICIA CLINICA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('60','OUTRAS ESPECIALIDADES','ACOLHIMENTO NOTURNO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('61','OUTRAS ESPECIALIDADES','CRONICOS');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('62','OUTRAS ESPECIALIDADES','PNEUMOLOGIA SANITARIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('63','OUTRAS ESPECIALIDADES','PSIQUIATRIA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('64','OUTRAS ESPECIALIDADES','REABILITACAO');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('65','PEDIATRICOS','PEDIATRIA CIRURGICA');
Insert into T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO,TP_LEITO,DS_ESPECIALIDADE) values ('66','PEDIATRICOS','PEDIATRIA CLINICA');

-- T_GRUPO_ICSAP (19 registros)
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('1','Doenças preveníveis por imunização e condições sensíveis','Doenças preveníveis por imunização e condições sensíveis');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('2','Gastroenterites infecciosas e complicações','Gastroenterites infecciosas e complicações');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('3','Anemia','Anemia');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('4','Deficiências nutricionais','Deficiências nutricionais');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('5','Infecções de ouvido, nariz e garganta','Infecções de ouvido, nariz e garganta');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('6','Pneumonias bacterianas','Pneumonias bacterianas');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('7','Asma','Asma');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('8','Doenças pulmonares','Doenças pulmonares');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('9','Hipertensão','Hipertensão');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('10','Angina','Angina');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('11','Insuficiência cardíaca','Insuficiência cardíaca');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('12','Doenças cerebrovasculares','Doenças cerebrovasculares');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('13','Diabetes mellitus','Diabetes mellitus');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('14','Epilepsias','Epilepsias');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('15','Infecção no rim e trato urinário','Infecção no rim e trato urinário');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('16','Infecção da pele e tecido subcutâneo','Infecção da pele e tecido subcutâneo');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('17','Doença inflamatória dos órgãos pélvicos femininos','Doença inflamatória dos órgãos pélvicos femininos');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('18','Úlcera gastrointestinal','Úlcera gastrointestinal');
Insert into T_GRUPO_ICSAP (ID_GRUPO_ICSAP,NM_GRUPO_ICSAP,DS_GRUPO_ICSAP) values ('19','Doenças relacionadas ao pré-natal e parto','Doenças relacionadas ao pré-natal e parto');

-- T_MUNICIPIO (20 registros)
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('351570','FERRAZ DE VASCONCELOS','SP','ALTO DO TIETE');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('351620','FRANCA','SP','TRES COLINAS');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('351880','GUARULHOS','SP','ALTO DO TIETE');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('352250','ITAPEVI','SP','ROTA DOS BANDEIRANTES');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('352500','JANDIRA','SP','ROTA DOS BANDEIRANTES');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('353060','MOGI DAS CRUZES','SP','ALTO DO TIETE');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('353440','OSASCO','SP','ROTA DOS BANDEIRANTES');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('353980','POA','SP','ALTO DO TIETE');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('354150','PRESIDENTE VENCESLAU','SP','EXTREMO OESTE PAULISTA');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('354570','SANTA ALBERTINA','SP','JALES');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('354980','SAO JOSE DO RIO PRETO','SP','SAO JOSE DO RIO PRETO');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('354990','SAO JOSE DOS CAMPOS','SP','ALTO VALE DO PARAIBA');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('355030','SAO PAULO','SP','SAO PAULO');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('355410','TAUBATE','SP','VALE DO PARAIBA/REGIAO SERRANA');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('355480','TREMEMBE','SP','VALE DO PARAIBA/REGIAO SERRANA');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('355580','URANIA','SP','JALES');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('350280','ARACATUBA','SP','CENTRAL DO DRS II');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('350570','BARUERI','SP','ROTA DOS BANDEIRANTES');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('351050','CARAGUATATUBA','SP','LITORAL NORTE');
Insert into T_MUNICIPIO (CD_MUNICIPIO,NM_MUNICIPIO,SG_UF,NM_REGIAO_SAUDE) values ('351518','ESPIRITO SANTO DO PINHAL','SP','MANTIQUEIRA');

-- T_FAIXA_ETARIA (9 registros)
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('1','Menor de 1 ano','0','0');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('3','5 a 9 anos','5','9');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('5','15 a 19 anos','15','19');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('6','20 a 29 anos','20','29');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('7','30 a 39 anos','30','39');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('9','50 a 59 anos','50','59');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('10','60 a 69 anos','60','69');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('11','70 a 79 anos','70','79');
Insert into T_FAIXA_ETARIA (ID_FAIXA_ETARIA,DS_FAIXA_ETARIA,NR_IDADE_MINIMA,NR_IDADE_MAXIMA) values ('12','80 anos ou mais','80',null);

-- T_PROCEDIMENTO (20 registros)
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0301060088','DIAGNOSTICO E/OU ATENDIMENTO DE URGENCIA EM CLINICA MEDICA','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303010037','TRATAMENTO DE OUTRAS DOENÇAS BACTERIANAS','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303030038','TRATAMENTO DE DIABETES MELLITUS','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303040149','TRATAMENTO DE ACIDENTE VASCULAR CEREBRAL - AVC (ISQUEMICO OU HEMORRAGICO AGUDO)','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303060190','TRATAMENTO DE INFARTO AGUDO DO MIOCÁRDIO','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303060212','TRATAMENTO DE INSUFICIENCIA CARDIACA','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303060301','TRATAMENTO DE VARIZES DOS MEMBROS INFERIORES C/ ULCERA','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303130059','TRATAMENTO DE PACIENTE SOB CUIDADOS PROLONGADOS POR ENFERMIDADES NEUROLOGICAS','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303160063','TRATAMENTO DE TRANSTORNOS RESPIRATORIOS E CARDIOVASCULARES ESPECIFICOS DO PERIODO NEONATAL','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303170140','TRATAMENTO CLÍNICO PARA CONTENÇÃO DE COMPORTAMENTO DESORGANIZADO E/OU DISRUPTIVO','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0303170190','TRATAMENTO EM PSIQUIATRIA DE CURTA PERMANENCIA POR DIA (PERMANENCIA ATÉ 90 DIAS)','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0304100021','TRATAMENTO CLÍNICO DE PACIENTE ONCOLÓGICO','03','Procedimentos clínicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0401020100','EXTIRPAÇÃOE SUPRESSÃO DE LESÃO DE PELE E DE TECIDO CELULAR SUBCUTÂNEO','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0404020500','OSTEOSSÍNTESE DA FRATURA COMPLEXA DA MANDÍBULA','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0404020550','OSTEOSSÍNTESE DE FRATURA SIMPLES DE MANDÍBULA','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0407020039','APENDICECTOMIA','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0407030034','COLECISTECTOMIA VIDEOLAPAROSCÓPICA','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0407040102','HERNIOPLASTIA INGUINAL / CRURAL (UNILATERAL)','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0408010185','TRATAMENTO CIRURGICO DE LUXACAO / FRATURA-LUXACAO ACROMIO-CLAVICULAR','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');
Insert into T_PROCEDIMENTO (CD_PROCEDIMENTO,DS_PROCEDIMENTO,CD_GRUPO_PROCEDIMENTO,NM_GRUPO_PROCEDIMENTO,TP_COMPLEXIDADE) values ('0411020013','CURETAGEM POS-ABORTAMENTO / PUERPERAL','04','Procedimentos cirúrgicos','MEDIA COMPLEXIDADE');

-- T_RACA_COR (3 registros)
Insert into T_RACA_COR (CD_RACA_COR,DS_RACA_COR) values ('01','BRANCA');
Insert into T_RACA_COR (CD_RACA_COR,DS_RACA_COR) values ('02','PRETA');
Insert into T_RACA_COR (CD_RACA_COR,DS_RACA_COR) values ('03','PARDA');

-- T_SEXO (2 registros)
Insert into T_SEXO (CD_SEXO,DS_SEXO) values ('1','MASCULINO');
Insert into T_SEXO (CD_SEXO,DS_SEXO) values ('3','FEMININO');

-- T_DIAGNOSTICO (19 registros)
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('A419','A41','Septicemia não especificada',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('C409','C40','Neoplasia maligna dos ossos e cartilagens articulares de membro não especificado',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('E141','E14','Diabetes mellitus não especificado - com cetoacidose','13');
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('F200','F20','Esquizofrenia paranóide',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('F202','F20','Esquizofrenia catatônica',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('G801','G80','Paralisia cerebral diplégica espástica',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('G811','G81','Hemiplegia espástica',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('I211','I21','Infarto agudo transmural da parede inferior do miocárdio',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('I500','I50','Insuficiência cardíaca congestiva','11');
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('I64','I64','Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico','12');
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('I830','I83','Varizes dos membros inferiores com úlcera',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('K359','K35','Apendicite aguda sem outra especificação',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('K40','K40','Hérnia inguinal',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('K800','K80','Calculose da vesícula biliar com colicistite aguda',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('L989','L98','Afecções da pele e do tecido subcutâneo, não especificados',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('O044','O04','Aborto por razões médicas e legais - incompleto, sem complicações',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('P228','P22','Outros desconfortos respiratórios do recém-nascido',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('S026','S02','Fratura de mandíbula',null);
Insert into T_DIAGNOSTICO (CD_CID10,CD_CATEGORIA_CID10,DS_DIAGNOSTICO,ID_GRUPO_ICSAP) values ('S431','S43','Luxação da articulação acromioclavicular',null);

-- T_ESTABELECIMENTO (21 registros)
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('0008052','353440','HOSPITAL REGIONAL DR VIVALDO MARTINS SIMOES OSASCO','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('0009628','354990','HOSPITAL MUNICIPAL DR JOSE DE CARVALHO FLORENCE','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('0092894','351050','HOSPITAL REGIONAL DO LITORAL NORTE','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('0127604','350570','HOSPITAL DE RETAGUARDA DO JARDIM PAULISTA','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('0161438','355030','HOSPITAL MUNICIPAL GUARAPIRANGA','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2066572','355030','HOSPITAL HELIOPOLIS UNIDADE DE GESTAO ASSISTENCIAL I','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2076896','355030','HOSPITAL SAO LUIZ GONZAGA','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2077396','354980','HOSPITAL DE BASE DE SAO JOSE DO RIO PRETO','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2077485','355030','HOSPITAL SAO PAULO HOSPITAL DE ENSINO DA UNIFESP','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2077639','355030','HOSP MUN PROF DR WALDOMIRO DE PAULA','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2078139','354150','SANTA CASA DE PRESIDENTE VENCESLAU','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2080079','351570','HOSPITAL DR OSIRIS FLORINDO COELHO','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2082276','351880','CASAS ANDRE LUIZ GUARULHOS','HOSPITAL ESPECIALIZADO');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2082675','350280','ASSOCIACAO DE AMPARO AO EXCEPCIONAL RITINHA PRATES','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2084384','351518','INSTITUTO BEZERRA DE MENEZES ESPIRITO SANTO DO PINHAL','HOSPITAL ESPECIALIZADO');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2705982','351620','SANTA CASA DE FRANCA','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('2749319','355410','HOSPITAL MUNICIPAL UNIVERSITARIO DE TAUBATE','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('3212130','355030','HOSP MUN VER JOSE STOROPOLLI','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('6236596','354980','HOSPITAL ESTADUAL JOAO PAULO II SAO JOSE DO RIO PRETO','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('7473702','353060','HOSP MUN DE MOGI DAS CRUZES PREF WALDEMAR COSTA FILHO','HOSPITAL GERAL');
Insert into T_ESTABELECIMENTO (CD_CNES,CD_MUNICIPIO,NM_ESTABELECIMENTO,TP_ESTABELECIMENTO) values ('9465464','355030','HOSP MUN JOSANIAS CASTANHA BRAGA','HOSPITAL GERAL');

-- T_CAPACIDADE_LEITO (42 registros)
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('855','2066572','1',DATE '2023-01-01','4','4');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('856','2066572','3',DATE '2023-01-01','86','86');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('969','2076896','3',DATE '2023-01-01','41','41');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('970','2076896','6',DATE '2023-01-01','5','5');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1012','2077396','3',DATE '2023-01-01','319','208');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1013','2077396','20',DATE '2023-01-01','399','246');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('16','0008052','1',DATE '2023-01-01','4','4');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('17','0008052','3',DATE '2023-01-01','19','19');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('74','0009628','3',DATE '2023-01-01','72','72');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('75','0009628','20',DATE '2023-01-01','98','98');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('127','0092894','3',DATE '2023-01-01','73','73');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('128','0092894','20',DATE '2023-01-01','63','63');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('141','0127604','20',DATE '2023-01-01','54','54');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('142','0127604','34',DATE '2023-01-01','5','5');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('147','0161438','20',DATE '2023-01-01','50','50');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('148','0161438','34',DATE '2023-01-01','100','100');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1295','2077639','3',DATE '2023-01-01','27','27');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1296','2077639','20',DATE '2023-01-01','40','39');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1510','2078139','3',DATE '2023-01-01','20','12');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1511','2078139','20',DATE '2023-01-01','26','17');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('2424','2080079','1',DATE '2023-01-01','1','1');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('2425','2080079','3',DATE '2023-01-01','22','22');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1108','2077485','2',DATE '2023-01-01','22','22');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('1109','2077485','3',DATE '2023-01-01','114','94');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('3755','2082675','39',DATE '2023-01-01','2','2');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('3756','2082675','61',DATE '2023-01-01','60','60');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('3554','2082276','61',DATE '2023-01-01','600','600');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('5079','2705982','1',DATE '2023-01-01','1','1');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('5080','2705982','2',DATE '2023-01-01','9','9');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('5312','2749319','3',DATE '2023-01-01','30','30');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('5313','2749319','20',DATE '2023-01-01','73','73');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('4233','2084384','63',DATE '2023-01-01','248','248');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('7158','6236596','3',DATE '2023-01-01','60','60');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('7159','6236596','20',DATE '2023-01-01','12','12');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('6279','3212130','3',DATE '2023-01-01','28','28');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('6280','3212130','11',DATE '2023-01-01','15','15');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('7628','7473702','3',DATE '2023-01-01','8','8');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('7629','7473702','6',DATE '2023-01-01','8','8');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('8085','9465464','3',DATE '2023-01-01','54','54');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('8086','9465464','11',DATE '2023-01-01','26','26');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('11864','2082276','61',DATE '2023-02-01','600','600');
Insert into T_CAPACIDADE_LEITO (ID_CAPACIDADE_LEITO,CD_CNES,ID_CATEGORIA_LEITO,DT_COMPETENCIA,QT_LEITOS_EXISTENTES,QT_LEITOS_SUS) values ('12543','2084384','63',DATE '2023-02-01','248','248');

-- T_PERFIL_INTERNACAO (21 registros)
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('126691',DATE '2023-01-01','355030','2077485','I500','0303060212','10','3','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('164918',DATE '2023-01-01','355480','2749319','K359','0407020039','3','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('445872',DATE '2023-03-01','354570','6236596','K800','0407030034','10','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('524047',DATE '2023-04-01','350280','2082675','G801','0303130059','6','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('929052',DATE '2023-06-01','351880','2082276','G811','0303130059','6','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('1197337',DATE '2023-07-01','355030','2076896','O044','0411020013','7','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('1679062',DATE '2023-10-01','352250','0008052','S026','0404020500','7','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('2288128',DATE '2024-01-01','355030','0161438','I211','0303060190','10','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('3436887',DATE '2024-07-01','354990','0009628','S026','0404020550','7','1','02');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('3585319',DATE '2024-08-01','353060','7473702','I830','0303060301','11','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('3691216',DATE '2024-08-01','355580','2077396','C409','0304100021','7','3','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('3736651',DATE '2024-09-01','351518','2084384','F202','0303170190','11','3','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('4071958',DATE '2024-10-01','355030','9465464','S431','0408010185','5','1','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('4426416',DATE '2024-12-01','355030','2077639','P228','0303160063','1','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('4924251',DATE '2025-03-01','352500','0127604','I64','0303040149','9','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('4963035',DATE '2025-03-01','354150','2078139','F200','0303170140','10','3','03');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('4994643',DATE '2025-03-01','355030','2066572','K40','0407040102','11','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('5095122',DATE '2025-04-01','351620','2705982','E141','0303030038','6','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('5510777',DATE '2025-06-01','351880','3212130','L989','0401020100','10','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('5685075',DATE '2025-07-01','351050','0092894','A419','0303010037','12','1','01');
Insert into T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO,DT_COMPETENCIA,CD_MUNICIPIO_RESIDENCIA,CD_CNES,CD_CID10,CD_PROCEDIMENTO,ID_FAIXA_ETARIA,CD_SEXO,CD_RACA_COR) values ('5765301',DATE '2025-07-01','353980','2080079','I64','0301060088','10','1','01');

-- T_RESUMO_AIH (21 registros)
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('126691','126691','3','0',31985.73);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('164918','164918','1','0',744.26);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('445872','445872','1','0',1033.23);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('524047','524047','1','1',2118.3);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('929052','929052','1','1',2118.3);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('1197337','1197337','1','0',261.18);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('1679062','1679062','1','0',950.94);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('2288128','2288128','1','0',781.71);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('3436887','3436887','1','0',503.19);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('3585319','3585319','1','0',4912.6);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('3691216','3691216','1','0',797.11);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('3736651','3736651','1','1',1830.17);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('4071958','4071958','1','0',404.47);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('4426416','4426416','4','0',5069.5);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('4924251','4924251','1','0',463.21);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('4963035','4963035','1','0','0');
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('4994643','4994643','1','0',739.97);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('5095122','5095122','1','0',541.19);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('5510777','5510777','1','0',198.89);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('5685075','5685075','1','0',15506.67);
Insert into T_RESUMO_AIH (ID_RESUMO_AIH,ID_PERFIL_INTERNACAO,QT_REGISTROS_AIH,QT_CONTINUIDADES_AIH,VL_TOTAL_AIH) values ('5765301','5765301','1','0',141.66);

-- T_RESUMO_ASSISTENCIAL (21 registros)
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('126691','126691','3','3','3',31985.73,31985.73,'33','3','1');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('164918','164918','1','1','0','0',744.26,'6','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('445872','445872','1','1','0','0',1033.23,'2','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('524047','524047','0','0','0','0',2118.3,'30','0','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('929052','929052','0','0','0','0',2118.3,'30','0','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('1197337','1197337','1','1','0','0',261.18,'1','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('1679062','1679062','1','1','0','0',950.94,'2','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('2288128','2288128','1','1','0','0',781.71,'9','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('3436887','3436887','1','1','0','0',503.19,'1','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('3585319','3585319','1','1','0','0',4912.6,'14','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('3691216','3691216','1','1','0','0',797.11,'2','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('3736651','3736651','0','0','0','0',1830.17,'30','0','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('4071958','4071958','1','1','0','0',404.47,'1','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('4426416','4426416','4','4','0','0',5069.5,'17','4','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('4924251','4924251','1','1','1',463.21,463.21,'3','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('4963035','4963035','1','1','0','0','0','5','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('4994643','4994643','1','1','0','0',739.97,'1','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('5095122','5095122','1','1','1',541.19,541.19,'2','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('5510777','5510777','1','1','0','0',198.89,'0','1','0');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('5685075','5685075','1','1','0','0',15506.67,'24','1','1');
Insert into T_RESUMO_ASSISTENCIAL (ID_RESUMO_ASSISTENCIAL,ID_PERFIL_INTERNACAO,QT_INTERNACOES,QT_INTERNACOES_ELEGIVEIS_ICSAP,QT_INTERNACOES_ICSAP,VL_TOTAL_ICSAP,VL_TOTAL_ELEGIVEL_IEP,QT_DIAS_PERMANENCIA,QT_SAIDAS_HOSPITALARES,QT_OBITOS) values ('5765301','5765301','1','1','1',141.66,141.66,'4','1','0');

COMMIT;
