-- Consultas para Oracle SQL Developer.
-- Pré-requisito: sql/mini/01_ddl.sql e sql/mini/02_dml.sql.

SELECT p.ID_PERFIL_INTERNACAO, p.DT_COMPETENCIA,
       m.NM_MUNICIPIO, e.NM_ESTABELECIMENTO,
       d.DS_DIAGNOSTICO, pr.DS_PROCEDIMENTO
FROM T_PERFIL_INTERNACAO p
JOIN T_MUNICIPIO m ON m.CD_MUNICIPIO = p.CD_MUNICIPIO_RESIDENCIA
JOIN T_ESTABELECIMENTO e ON e.CD_CNES = p.CD_CNES
JOIN T_DIAGNOSTICO d ON d.CD_CID10 = p.CD_CID10
JOIN T_PROCEDIMENTO pr ON pr.CD_PROCEDIMENTO = p.CD_PROCEDIMENTO
ORDER BY p.DT_COMPETENCIA, m.NM_MUNICIPIO;

SELECT m.NM_MUNICIPIO, SUM(a.QT_INTERNACOES) AS QT_INTERNACOES
FROM T_RESUMO_ASSISTENCIAL a
JOIN T_PERFIL_INTERNACAO p ON p.ID_PERFIL_INTERNACAO = a.ID_PERFIL_INTERNACAO
JOIN T_MUNICIPIO m ON m.CD_MUNICIPIO = p.CD_MUNICIPIO_RESIDENCIA
GROUP BY m.NM_MUNICIPIO
ORDER BY QT_INTERNACOES DESC;

SELECT EXTRACT(YEAR FROM DT_COMPETENCIA) AS ANO, COUNT(*) AS QT_PERFIS
FROM T_PERFIL_INTERNACAO
GROUP BY EXTRACT(YEAR FROM DT_COMPETENCIA)
ORDER BY ANO;

SELECT d.ID_GRUPO_ICSAP, g.NM_GRUPO_ICSAP,
       SUM(a.QT_INTERNACOES_ICSAP) AS QT_INTERNACOES_ICSAP
FROM T_DIAGNOSTICO d
JOIN T_PERFIL_INTERNACAO p ON p.CD_CID10 = d.CD_CID10
JOIN T_GRUPO_ICSAP g ON g.ID_GRUPO_ICSAP = d.ID_GRUPO_ICSAP
JOIN T_RESUMO_ASSISTENCIAL a ON a.ID_PERFIL_INTERNACAO = p.ID_PERFIL_INTERNACAO
WHERE d.ID_GRUPO_ICSAP IS NOT NULL
GROUP BY d.ID_GRUPO_ICSAP, g.NM_GRUPO_ICSAP
ORDER BY QT_INTERNACOES_ICSAP DESC;
