-- HUBSUS360 - SCRIPT DDL COMPLETO
-- Enterprise Challenge Oracle x FIAP 2026 - Sprint 3
-- Turma: 1TSCPF
-- Grupo: GP3L
--
-- Integrantes:
-- Guilherme Ladeira Correa Santos - 
-- Lucas Amaral da Silva Barros    - 
-- Lucas Araújo Curci              - 
-- Lucas Luna Pimentel             - 
-- Pedro Henrique Moretti Aguiar   - 
--
-- Banco: Oracle Autonomous Database 26ai
-- Schema: ADMIN

-- DROPS COMENTADOS
-- DROP TABLE T_RESUMO_ASSISTENCIAL CASCADE CONSTRAINTS;
-- DROP TABLE T_RESUMO_AIH CASCADE CONSTRAINTS;
-- DROP TABLE T_PERFIL_INTERNACAO CASCADE CONSTRAINTS;
-- DROP TABLE T_CAPACIDADE_LEITO CASCADE CONSTRAINTS;
-- DROP TABLE T_CATEGORIA_LEITO CASCADE CONSTRAINTS;
-- DROP TABLE T_RACA_COR CASCADE CONSTRAINTS;
-- DROP TABLE T_SEXO CASCADE CONSTRAINTS;
-- DROP TABLE T_FAIXA_ETARIA CASCADE CONSTRAINTS;
-- DROP TABLE T_PROCEDIMENTO CASCADE CONSTRAINTS;
-- DROP TABLE T_ESTABELECIMENTO CASCADE CONSTRAINTS;
-- DROP TABLE T_MUNICIPIO CASCADE CONSTRAINTS;
-- DROP TABLE T_DIAGNOSTICO CASCADE CONSTRAINTS;
-- DROP TABLE T_GRUPO_ICSAP CASCADE CONSTRAINTS;

CREATE TABLE T_GRUPO_ICSAP (
    ID_GRUPO_ICSAP NUMBER(2) NOT NULL,
    NM_GRUPO_ICSAP VARCHAR2(100) NOT NULL,
    DS_GRUPO_ICSAP VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_GRUPO_ICSAP PRIMARY KEY (ID_GRUPO_ICSAP),
    CONSTRAINT UK_GRUPO_ICSAP_NOME UNIQUE (NM_GRUPO_ICSAP),
    CONSTRAINT CK_GRUPO_ICSAP_ID CHECK (ID_GRUPO_ICSAP BETWEEN 1 AND 19)
);

CREATE TABLE T_DIAGNOSTICO (
    CD_CID10 VARCHAR2(5) NOT NULL,
    CD_CATEGORIA_CID10 VARCHAR2(3) NOT NULL,
    DS_DIAGNOSTICO VARCHAR2(500) NOT NULL,
    ID_GRUPO_ICSAP NUMBER(2),
    CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (CD_CID10),
    CONSTRAINT FK_DIAG_GRUPO_ICSAP FOREIGN KEY (ID_GRUPO_ICSAP)
        REFERENCES T_GRUPO_ICSAP (ID_GRUPO_ICSAP),
    CONSTRAINT CK_DIAG_CATEGORIA CHECK (LENGTH(CD_CATEGORIA_CID10) = 3)
);

CREATE INDEX IX_DIAG_GRUPO_ICSAP ON T_DIAGNOSTICO (ID_GRUPO_ICSAP);

CREATE TABLE T_MUNICIPIO (
    CD_MUNICIPIO CHAR(6) NOT NULL,
    NM_MUNICIPIO VARCHAR2(60) NOT NULL,
    SG_UF CHAR(2) NOT NULL,
    NM_REGIAO_SAUDE VARCHAR2(80) NOT NULL,
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY (CD_MUNICIPIO),
    CONSTRAINT UK_MUNICIPIO_NOME_UF UNIQUE (NM_MUNICIPIO, SG_UF),
    CONSTRAINT CK_MUNICIPIO_UF CHECK (SG_UF = 'SP')
);

CREATE INDEX IX_MUNICIPIO_REGIAO_SAUDE ON T_MUNICIPIO (NM_REGIAO_SAUDE);

CREATE TABLE T_ESTABELECIMENTO (
    CD_CNES CHAR(7) NOT NULL,
    CD_MUNICIPIO CHAR(6) NOT NULL,
    NM_ESTABELECIMENTO VARCHAR2(100) NOT NULL,
    TP_ESTABELECIMENTO VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ESTABELECIMENTO PRIMARY KEY (CD_CNES),
    CONSTRAINT FK_ESTAB_MUNICIPIO FOREIGN KEY (CD_MUNICIPIO)
        REFERENCES T_MUNICIPIO (CD_MUNICIPIO)
);

CREATE INDEX IX_ESTAB_MUNICIPIO ON T_ESTABELECIMENTO (CD_MUNICIPIO);
CREATE INDEX IX_ESTAB_TIPO ON T_ESTABELECIMENTO (TP_ESTABELECIMENTO);

CREATE TABLE T_PROCEDIMENTO (
    CD_PROCEDIMENTO CHAR(10) NOT NULL,
    DS_PROCEDIMENTO VARCHAR2(250) NOT NULL,
    CD_GRUPO_PROCEDIMENTO CHAR(2) NOT NULL,
    NM_GRUPO_PROCEDIMENTO VARCHAR2(80) NOT NULL,
    TP_COMPLEXIDADE VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PROCEDIMENTO PRIMARY KEY (CD_PROCEDIMENTO),
    CONSTRAINT CK_PROC_COMPLEXIDADE CHECK (
        TP_COMPLEXIDADE IN ('ALTA COMPLEXIDADE','MEDIA COMPLEXIDADE','NAO SE APLICA')
    ),
    CONSTRAINT CK_PROC_GRUPO CHECK (CD_GRUPO_PROCEDIMENTO IN ('02','03','04','05'))
);

CREATE INDEX IX_PROC_GRUPO ON T_PROCEDIMENTO (CD_GRUPO_PROCEDIMENTO);
CREATE INDEX IX_PROC_COMPLEXIDADE ON T_PROCEDIMENTO (TP_COMPLEXIDADE);

CREATE TABLE T_FAIXA_ETARIA (
    ID_FAIXA_ETARIA NUMBER(2) NOT NULL,
    DS_FAIXA_ETARIA VARCHAR2(40) NOT NULL,
    NR_IDADE_MINIMA NUMBER(3),
    NR_IDADE_MAXIMA NUMBER(3),
    CONSTRAINT PK_FAIXA_ETARIA PRIMARY KEY (ID_FAIXA_ETARIA),
    CONSTRAINT UK_FAIXA_ETARIA_DESC UNIQUE (DS_FAIXA_ETARIA),
    CONSTRAINT CK_FAIXA_ETARIA_ID CHECK (ID_FAIXA_ETARIA BETWEEN 1 AND 13),
    CONSTRAINT CK_FAIXA_ETARIA_LIMITES CHECK (
        NR_IDADE_MINIMA IS NULL
        OR NR_IDADE_MAXIMA IS NULL
        OR NR_IDADE_MINIMA <= NR_IDADE_MAXIMA
    )
);

CREATE TABLE T_SEXO (
    CD_SEXO CHAR(1) NOT NULL,
    DS_SEXO VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_SEXO PRIMARY KEY (CD_SEXO),
    CONSTRAINT UK_SEXO_DESC UNIQUE (DS_SEXO),
    CONSTRAINT CK_SEXO_CODIGO CHECK (CD_SEXO IN ('1','3'))
);

CREATE TABLE T_RACA_COR (
    CD_RACA_COR CHAR(2) NOT NULL,
    DS_RACA_COR VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_RACA_COR PRIMARY KEY (CD_RACA_COR),
    CONSTRAINT UK_RACA_COR_DESC UNIQUE (DS_RACA_COR),
    CONSTRAINT CK_RACA_COR_CODIGO CHECK (CD_RACA_COR IN ('01','02','03','04','05','99'))
);

CREATE TABLE T_CATEGORIA_LEITO (
    ID_CATEGORIA_LEITO NUMBER(2) NOT NULL,
    TP_LEITO VARCHAR2(40) NOT NULL,
    DS_ESPECIALIDADE VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CATEGORIA_LEITO PRIMARY KEY (ID_CATEGORIA_LEITO),
    CONSTRAINT UK_CATEGORIA_LEITO UNIQUE (TP_LEITO, DS_ESPECIALIDADE),
    CONSTRAINT CK_CATEGORIA_LEITO_ID CHECK (ID_CATEGORIA_LEITO BETWEEN 1 AND 66)
);

CREATE INDEX IX_CAT_LEITO_TIPO ON T_CATEGORIA_LEITO (TP_LEITO);

CREATE TABLE T_CAPACIDADE_LEITO (
    ID_CAPACIDADE_LEITO NUMBER(10) NOT NULL,
    CD_CNES CHAR(7) NOT NULL,
    ID_CATEGORIA_LEITO NUMBER(2) NOT NULL,
    DT_COMPETENCIA DATE NOT NULL,
    QT_LEITOS_EXISTENTES NUMBER(6) NOT NULL,
    QT_LEITOS_SUS NUMBER(6) NOT NULL,
    CONSTRAINT PK_CAPACIDADE_LEITO PRIMARY KEY (ID_CAPACIDADE_LEITO),
    CONSTRAINT FK_CAP_LEITO_ESTAB FOREIGN KEY (CD_CNES)
        REFERENCES T_ESTABELECIMENTO (CD_CNES),
    CONSTRAINT FK_CAP_LEITO_CATEG FOREIGN KEY (ID_CATEGORIA_LEITO)
        REFERENCES T_CATEGORIA_LEITO (ID_CATEGORIA_LEITO),
    CONSTRAINT UK_CAP_LEITO_NEGOCIO UNIQUE (CD_CNES, ID_CATEGORIA_LEITO, DT_COMPETENCIA),
    CONSTRAINT CK_CAP_LEITOS_EXIST CHECK (QT_LEITOS_EXISTENTES >= 0),
    CONSTRAINT CK_CAP_LEITOS_SUS CHECK (QT_LEITOS_SUS >= 0),
    CONSTRAINT CK_CAP_SUS_TOTAL CHECK (QT_LEITOS_SUS <= QT_LEITOS_EXISTENTES)
);

CREATE INDEX IX_CAP_LEITO_CNES ON T_CAPACIDADE_LEITO (CD_CNES);
CREATE INDEX IX_CAP_LEITO_COMP ON T_CAPACIDADE_LEITO (DT_COMPETENCIA);

CREATE TABLE T_PERFIL_INTERNACAO (
    ID_PERFIL_INTERNACAO NUMBER(8) NOT NULL,
    DT_COMPETENCIA DATE NOT NULL,
    CD_MUNICIPIO_RESIDENCIA CHAR(6) NOT NULL,
    CD_CNES CHAR(7) NOT NULL,
    CD_CID10 VARCHAR2(5) NOT NULL,
    CD_PROCEDIMENTO CHAR(10) NOT NULL,
    ID_FAIXA_ETARIA NUMBER(2) NOT NULL,
    CD_SEXO CHAR(1) NOT NULL,
    CD_RACA_COR CHAR(2) NOT NULL,
    CONSTRAINT PK_PERFIL_INTERNACAO PRIMARY KEY (ID_PERFIL_INTERNACAO),
    CONSTRAINT FK_PERFIL_MUNICIPIO FOREIGN KEY (CD_MUNICIPIO_RESIDENCIA)
        REFERENCES T_MUNICIPIO (CD_MUNICIPIO),
    CONSTRAINT FK_PERFIL_ESTAB FOREIGN KEY (CD_CNES)
        REFERENCES T_ESTABELECIMENTO (CD_CNES),
    CONSTRAINT FK_PERFIL_DIAG FOREIGN KEY (CD_CID10)
        REFERENCES T_DIAGNOSTICO (CD_CID10),
    CONSTRAINT FK_PERFIL_PROC FOREIGN KEY (CD_PROCEDIMENTO)
        REFERENCES T_PROCEDIMENTO (CD_PROCEDIMENTO),
    CONSTRAINT FK_PERFIL_FAIXA FOREIGN KEY (ID_FAIXA_ETARIA)
        REFERENCES T_FAIXA_ETARIA (ID_FAIXA_ETARIA),
    CONSTRAINT FK_PERFIL_SEXO FOREIGN KEY (CD_SEXO)
        REFERENCES T_SEXO (CD_SEXO),
    CONSTRAINT FK_PERFIL_RACA FOREIGN KEY (CD_RACA_COR)
        REFERENCES T_RACA_COR (CD_RACA_COR)
);

CREATE TABLE T_RESUMO_AIH (
    ID_RESUMO_AIH NUMBER(8) NOT NULL,
    ID_PERFIL_INTERNACAO NUMBER(8) NOT NULL,
    QT_REGISTROS_AIH NUMBER(3) NOT NULL,
    QT_CONTINUIDADES_AIH NUMBER(3) NOT NULL,
    VL_TOTAL_AIH NUMBER(12,2) NOT NULL,
    CONSTRAINT PK_RESUMO_AIH PRIMARY KEY (ID_RESUMO_AIH),
    CONSTRAINT FK_RESUMO_AIH_PERFIL FOREIGN KEY (ID_PERFIL_INTERNACAO)
        REFERENCES T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO),
    CONSTRAINT UK_RESUMO_AIH_PERFIL UNIQUE (ID_PERFIL_INTERNACAO),
    CONSTRAINT CK_RES_AIH_REGISTROS CHECK (QT_REGISTROS_AIH >= 1),
    CONSTRAINT CK_RES_AIH_CONTINUIDADES CHECK (
        QT_CONTINUIDADES_AIH >= 0
        AND QT_CONTINUIDADES_AIH <= QT_REGISTROS_AIH
    ),
    CONSTRAINT CK_RES_AIH_VALOR CHECK (VL_TOTAL_AIH >= 0)
);

CREATE TABLE T_RESUMO_ASSISTENCIAL (
    ID_RESUMO_ASSISTENCIAL NUMBER(8) NOT NULL,
    ID_PERFIL_INTERNACAO NUMBER(8) NOT NULL,
    QT_INTERNACOES NUMBER(10) NOT NULL,
    QT_INTERNACOES_ELEGIVEIS_ICSAP NUMBER(10) NOT NULL,
    QT_INTERNACOES_ICSAP NUMBER(10) NOT NULL,
    VL_TOTAL_ICSAP NUMBER(14,2) NOT NULL,
    VL_TOTAL_ELEGIVEL_IEP NUMBER(14,2) NOT NULL,
    QT_DIAS_PERMANENCIA NUMBER(12) NOT NULL,
    QT_SAIDAS_HOSPITALARES NUMBER(10) NOT NULL,
    QT_OBITOS NUMBER(10) NOT NULL,
    CONSTRAINT PK_RESUMO_ASSISTENCIAL PRIMARY KEY (ID_RESUMO_ASSISTENCIAL),
    CONSTRAINT FK_RES_ASSIST_PERFIL FOREIGN KEY (ID_PERFIL_INTERNACAO)
        REFERENCES T_PERFIL_INTERNACAO (ID_PERFIL_INTERNACAO),
    CONSTRAINT UK_RES_ASSIST_PERFIL UNIQUE (ID_PERFIL_INTERNACAO),
    CONSTRAINT CK_RES_ASSIST_INTERNACOES CHECK (QT_INTERNACOES >= 0),
    CONSTRAINT CK_RES_ASSIST_ELEGIVEIS CHECK (
        QT_INTERNACOES_ELEGIVEIS_ICSAP >= 0
        AND QT_INTERNACOES_ELEGIVEIS_ICSAP <= QT_INTERNACOES
    ),
    CONSTRAINT CK_RES_ASSIST_ICSAP CHECK (
        QT_INTERNACOES_ICSAP >= 0
        AND QT_INTERNACOES_ICSAP <= QT_INTERNACOES_ELEGIVEIS_ICSAP
    ),
    CONSTRAINT CK_RES_ASSIST_VL_ICSAP CHECK (VL_TOTAL_ICSAP >= 0),
    CONSTRAINT CK_RES_ASSIST_VL_IEP CHECK (VL_TOTAL_ELEGIVEL_IEP >= 0),
    CONSTRAINT CK_RES_ASSIST_DIAS CHECK (QT_DIAS_PERMANENCIA >= 0),
    CONSTRAINT CK_RES_ASSIST_SAIDAS CHECK (QT_SAIDAS_HOSPITALARES >= 0),
    CONSTRAINT CK_RES_ASSIST_OBITOS CHECK (
        QT_OBITOS >= 0
        AND QT_OBITOS <= QT_SAIDAS_HOSPITALARES
    )
);

-- COMMENTS PRINCIPAIS PARA SELECT AI
COMMENT ON TABLE T_GRUPO_ICSAP IS 'Dimensao de grupos de Condicoes Sensiveis a Atencao Primaria (ICSAP).';
COMMENT ON TABLE T_DIAGNOSTICO IS 'Dimensao de diagnosticos CID-10 utilizados nas internacoes hospitalares.';
COMMENT ON TABLE T_MUNICIPIO IS 'Dimensao de municipios do estado de Sao Paulo e respectivas regioes de saude.';
COMMENT ON TABLE T_ESTABELECIMENTO IS 'Dimensao de estabelecimentos de saude identificados pelo CNES.';
COMMENT ON TABLE T_PROCEDIMENTO IS 'Dimensao de procedimentos hospitalares realizados no SUS.';
COMMENT ON TABLE T_FAIXA_ETARIA IS 'Dimensao de faixas etarias utilizadas na classificacao dos pacientes.';
COMMENT ON TABLE T_SEXO IS 'Dimensao de sexo dos pacientes conforme codificacao utilizada nos dados hospitalares.';
COMMENT ON TABLE T_RACA_COR IS 'Dimensao de raca ou cor dos pacientes conforme codificacao dos dados hospitalares.';
COMMENT ON TABLE T_CATEGORIA_LEITO IS 'Dimensao de categorias de leitos hospitalares por tipo e especialidade.';
COMMENT ON TABLE T_CAPACIDADE_LEITO IS 'Fato mensal de capacidade de leitos por estabelecimento CNES, categoria e competencia.';
COMMENT ON TABLE T_PERFIL_INTERNACAO IS 'Tabela central de perfis analiticos de internacao por competencia, municipio, estabelecimento, diagnostico, procedimento e caracteristicas demograficas.';
COMMENT ON TABLE T_RESUMO_AIH IS 'Resumo financeiro e quantitativo dos registros de AIH associados a cada perfil de internacao.';
COMMENT ON TABLE T_RESUMO_ASSISTENCIAL IS 'Resumo assistencial por perfil de internacao, incluindo internacoes, ICSAP, permanencia, saidas hospitalares, obitos e valores elegiveis para indicadores.';

COMMENT ON COLUMN T_DIAGNOSTICO.DS_DIAGNOSTICO IS 'Descricao textual do diagnostico CID-10.';
COMMENT ON COLUMN T_DIAGNOSTICO.ID_GRUPO_ICSAP IS 'Identificador do grupo ICSAP ao qual o diagnostico pertence, quando aplicavel.';
COMMENT ON COLUMN T_PROCEDIMENTO.DS_PROCEDIMENTO IS 'Descricao do procedimento hospitalar realizado no SUS.';
COMMENT ON COLUMN T_PROCEDIMENTO.NM_GRUPO_PROCEDIMENTO IS 'Nome do grupo do procedimento hospitalar.';
COMMENT ON COLUMN T_PROCEDIMENTO.TP_COMPLEXIDADE IS 'Nivel de complexidade assistencial associado ao procedimento.';
COMMENT ON COLUMN T_RESUMO_AIH.VL_TOTAL_AIH IS 'Valor total aprovado das AIHs associadas ao perfil de internacao, em reais.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.QT_INTERNACOES IS 'Quantidade de novas internacoes hospitalares associadas ao perfil.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.QT_INTERNACOES_ELEGIVEIS_ICSAP IS 'Quantidade de internacoes elegiveis para o calculo do indicador ICSAP.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.QT_INTERNACOES_ICSAP IS 'Quantidade de internacoes classificadas como Condicoes Sensiveis a Atencao Primaria.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.VL_TOTAL_ICSAP IS 'Valor financeiro total associado as internacoes classificadas como ICSAP.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.VL_TOTAL_ELEGIVEL_IEP IS 'Valor total elegivel utilizado no calculo do Indicador de Eficiencia Preventiva do HUBSUS360.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.QT_DIAS_PERMANENCIA IS 'Total de dias de permanencia hospitalar.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.QT_SAIDAS_HOSPITALARES IS 'Quantidade de saidas hospitalares utilizadas no calculo de indicadores assistenciais.';
COMMENT ON COLUMN T_RESUMO_ASSISTENCIAL.QT_OBITOS IS 'Quantidade de obitos hospitalares associados ao perfil de internacao.';

-- FIM
